image:
  repository: your-registry/your-django-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

config:
	POSTGRES_PORT: 5432
	POSTGRES_HOST: db 
	POSTGRES_PORT: 5432
	POSTGRES_USER: django_user
	POSTGRES_DB: django_db
	POSTGRES_PASSWORD: pass9764gd

